{
  "hash": "f508bc4b11308c85b282564dd2401c6e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Getting to Know Your Data\"\n---\n\n## Variables\n\nBefore we jump into the world of statistical testing, let’s take a moment to refresh our understanding of what a variable is, the different types of variables, and how we can describe them using numerical and graphical methods.\n\n**So what is a variable?**\n\nThe Australian Bureau of Statistics defines a variable to be \"any characteristic, number, or quantity that can be measured or counted.\"\n\nIf you’ve ever tried dieting, you might have recorded your weight on your phone over time. Or maybe you’ve tracked how long your morning commute takes so you know when to leave to arrive on time. In both cases, you are measuring something that changes, and these are examples of variables.\n\n## Types of Variables\n\nThere are two main types of variables:\n\n-   **Numerical**\n\n-   **Categorical**\n\nA **numerical variable** represents values to describe a measurable quantity. A numerical variable can be either **discrete** or **continuous**.\n\n**Discrete numerical variables** take on distinct whole values, and are countable. For example, if we were to look at the at the number of cars in a parking lot, the number of birds in a tree, or the number of times \"3\" is rolled in a series of die rolls, these are exact values that can be counted and are thus discrete.\n\n**Continuous numerical variables** can take on any value within a range of real numbers. In other words, they can be measured to any level of precision. For example, age exists on a continuous scale because, in theory, it can be measured infinitely precisely. Someone could be 10.25, 10.257, or even 10.2576326362 years old. In everyday life, we usually round age to the nearest year, but that does not change the fact that the underlying variable is continuous. Other common examples of continuous numerical variables include weight, height, and time. Can you explain why each of these variables is numerical and continuous?\n\nA **categorical variable**, on the other hand, represents categories or labels that describe a quality or characteristic. Categorical variables can be either **nominal** or **ordinal**.\n\nA **nominal categorical variable** includes observations with no particular order. For example, if you asked ten coworkers for their favorite movie and recorded their answers under a \"movies\" variable, it would be nominal because there is no inherent sequence or ranking among the movie titles.\n\nIn an **ordinal categorical variable,** there is an inherent logical order to the observations. For example, if we collected age groups such as \"18–24\", \"25–38\", \"39–55\", \"56–70\", and \"70+\", we’re now working with labels that have a built-in order where \"18–24\" is younger than \"25–38\", and so on.\n\nAnother example might be asking people whether they like ice cream, with options like \"strongly agree\", \"agree\", \"neutral\", \"disagree\", and \"strongly disagree\". In this case, the order of the options has meaning, even if the distance between them isn’t equal.\n\nTake a moment to check your understanding with the exercises below.\n\n## Exercise Checkpoint 1\n\n\n::: {.cell}\n\n:::\n\n\n1.  **Describe the following variables:**\n\n    a\\. Eye colour is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>continuous numerical variable</option><option value=''>ordinal categorical variable</option><option value='answer'>nominal categorical variable</option></select>\n\n    b\\. Temperature is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>ordinal categorical variable</option><option value=''>nominal categorical variable</option><option value='answer'>continuous numerical variable</option></select>\n\n    c\\. The number of heads in a series of coin flips is a <select class='webex-select'><option value='blank'></option><option value=''>continuous numerical variable</option><option value=''>ordinal categorical variable</option><option value=''>nominal categorical variable</option><option value='answer'>discrete numerical variable</option></select>\n\n    d\\. Education level is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>continuous numerical variable</option><option value=''>nominal categorical variable</option><option value='answer'>ordinal categorical variable</option></select>\n\n    e\\. Postal Code is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>continuous numerical variable</option><option value=''>ordinal categorical variable</option><option value='answer'>nominal categorical variable</option></select>\n\n    f\\. Income salary is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>ordinal categorical variable</option><option value=''>nominal categorical variable</option><option value='answer'>continuous numerical variable</option></select>\n\n    g\\. Number of calls per day is a <select class='webex-select'><option value='blank'></option><option value=''>discrete numerical variable</option><option value=''>continuous numerical variable</option><option value=''>ordinal categorical variable</option><option value=''>nominal categorical variable</option><option value='answer'>discrete numerical variable</option></select>\n\n## Visually Representing Data\n\nNow that we’ve covered the main types of variables, we can start thinking about how to visually represent data.\n\nFirst, we will need to load in some data into R. We will be working with the `palmerpenguins` package. The `palmerpenguins` package is a dataset collected and made available by [Dr. Kristen Gorman](https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php) and the [Palmer Station, Antarctica LTER](https://pallter.marine.rutgers.edu/), a member of the [Long Term Ecological Research Network](https://lternet.edu/).\n\nIf you have not used this package before, you will need to install it first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"palmerpenguins\")\n```\n:::\n\n\nOnce installed, you will need to load the package into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n```\n:::\n\n\nNow that we have the package installed, let’s take a look at the variables in the dataset using `str()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [344 × 8] (S3: tbl_df/tbl/data.frame)\n $ species          : Factor w/ 3 levels \"Adelie\",\"Chinstrap\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ island           : Factor w/ 3 levels \"Biscoe\",\"Dream\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...\n $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...\n $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...\n $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...\n $ sex              : Factor w/ 2 levels \"female\",\"male\": 2 1 1 NA 1 2 1 2 NA NA ...\n $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...\n```\n\n\n:::\n:::\n\n\nYou might notice that some values are listed as `NA`. This means there are missing observations. To check for missing values, we can use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(is.na(penguins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nSince this returns `TRUE`, we know there are missing values in the dataset. Let's find out how many:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(penguins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19\n```\n\n\n:::\n:::\n\n\nThere are 19 missing observations. This can cause problems when generating numerical summaries or running statistical tests. At this stage, to handle this, we can remove the missing values. It’s always best practice to store your cleaned data in a new dataset and leave the original untouched. **Note that you should always be careful when removing observations, as even partially filled observations can still provide valuable information.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_penguins <- na.omit(penguins)\n```\n:::\n\n\nWe can check the structure again to make sure everything looks good:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(clean_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [333 × 8] (S3: tbl_df/tbl/data.frame)\n $ species          : Factor w/ 3 levels \"Adelie\",\"Chinstrap\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ island           : Factor w/ 3 levels \"Biscoe\",\"Dream\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ bill_length_mm   : num [1:333] 39.1 39.5 40.3 36.7 39.3 38.9 39.2 41.1 38.6 34.6 ...\n $ bill_depth_mm    : num [1:333] 18.7 17.4 18 19.3 20.6 17.8 19.6 17.6 21.2 21.1 ...\n $ flipper_length_mm: int [1:333] 181 186 195 193 190 181 195 182 191 198 ...\n $ body_mass_g      : int [1:333] 3750 3800 3250 3450 3650 3625 4675 3200 3800 4400 ...\n $ sex              : Factor w/ 2 levels \"female\",\"male\": 2 1 1 1 2 1 2 1 2 2 ...\n $ year             : int [1:333] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...\n - attr(*, \"na.action\")= 'omit' Named int [1:11] 4 9 10 11 12 48 179 219 257 269 ...\n  ..- attr(*, \"names\")= chr [1:11] \"4\" \"9\" \"10\" \"11\" ...\n```\n\n\n:::\n:::\n\n\nWe can see that there are eight variables. Three of these are categorical: `species`, `island`, and `sex`. These are stored as factors, where the *levels* represent the number of distinct labels or groups within each variable. For example, `sex` has two levels: `male` and `female`.\n\nYou'll notice that there are four numerical variables: `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, and `year`. If your instinct is that `year` doesn't quite fit as right as a numerical variable, you would be right! It is better to treat `year` as a categorical variable. To convert it, we can use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_penguins$year <- as.factor(clean_penguins$year)\n```\n:::\n\n\nNow if we run `str` again, we can see that `year` is now correctly stored as a categorical variable with three levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(clean_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [333 × 8] (S3: tbl_df/tbl/data.frame)\n $ species          : Factor w/ 3 levels \"Adelie\",\"Chinstrap\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ island           : Factor w/ 3 levels \"Biscoe\",\"Dream\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ bill_length_mm   : num [1:333] 39.1 39.5 40.3 36.7 39.3 38.9 39.2 41.1 38.6 34.6 ...\n $ bill_depth_mm    : num [1:333] 18.7 17.4 18 19.3 20.6 17.8 19.6 17.6 21.2 21.1 ...\n $ flipper_length_mm: int [1:333] 181 186 195 193 190 181 195 182 191 198 ...\n $ body_mass_g      : int [1:333] 3750 3800 3250 3450 3650 3625 4675 3200 3800 4400 ...\n $ sex              : Factor w/ 2 levels \"female\",\"male\": 2 1 1 1 2 1 2 1 2 2 ...\n $ year             : Factor w/ 3 levels \"2007\",\"2008\",..: 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"na.action\")= 'omit' Named int [1:11] 4 9 10 11 12 48 179 219 257 269 ...\n  ..- attr(*, \"names\")= chr [1:11] \"4\" \"9\" \"10\" \"11\" ...\n```\n\n\n:::\n:::\n\n\nIf you're interested in seeing the unique groupings or labels within a categorical variable, you can use the `unique()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(clean_penguins$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2007 2008 2009\nLevels: 2007 2008 2009\n```\n\n\n:::\n:::\n\n\nThis shows that the data was collected over the years 2007, 2008, and 2009.\n\nYou can also see from the structure output `str()` that the `penguins` dataset is stored as a 333 x 8 tibble, which is a type of data frame in R. This means that there are 333 rows (observations) and 8 columns (variables).\n\nWe can confirm this using the `dim()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(clean_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 333   8\n```\n\n\n:::\n:::\n\n\nIf you wish to have a closer look at inspecting the `penguins` dataset, you can use the `View()` function to open it in a new tab on RStudio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(penguins)\nView(clean_penguins)\n```\n:::\n\n\nNow that we’ve inspected the dataset, we can start thinking about how to visually represent and understand the data.\n\nWe can describe data using numerical summaries and graphs. Numerical summaries are statistical measures that capture key aspects of a dataset. The way we choose to present these summaries and the graphs that accompany them depends on the type of variable we are working with.\n\nLet’s start with numerical summaries.\n\nFor **numerical variables**, whether continuous or discrete, we can include:\n\n-   mean\n\n-   standard deviation\n\n-   median\n\n-   minimum\n\n-   maximum\n\n-   Interquartile Range (IQR)\n\n**IMPORTANT NOTE:** When reporting descriptive statistics, always provide appropriate context. If you report a mean, include the standard deviation, and vice versa. If you report a median, include the interquartile range (IQR), and vice versa. Likewise, if you report a maximum value, always include the minimum to give full perspective.\n\nSome helpful R functions for generating summary statistics:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xztfpeeuwt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xztfpeeuwt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xztfpeeuwt thead, #xztfpeeuwt tbody, #xztfpeeuwt tfoot, #xztfpeeuwt tr, #xztfpeeuwt td, #xztfpeeuwt th {\n  border-style: none;\n}\n\n#xztfpeeuwt p {\n  margin: 0;\n  padding: 0;\n}\n\n#xztfpeeuwt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xztfpeeuwt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xztfpeeuwt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xztfpeeuwt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xztfpeeuwt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xztfpeeuwt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xztfpeeuwt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xztfpeeuwt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xztfpeeuwt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xztfpeeuwt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xztfpeeuwt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xztfpeeuwt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xztfpeeuwt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xztfpeeuwt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xztfpeeuwt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xztfpeeuwt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xztfpeeuwt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xztfpeeuwt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xztfpeeuwt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xztfpeeuwt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xztfpeeuwt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xztfpeeuwt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xztfpeeuwt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xztfpeeuwt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xztfpeeuwt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xztfpeeuwt .gt_left {\n  text-align: left;\n}\n\n#xztfpeeuwt .gt_center {\n  text-align: center;\n}\n\n#xztfpeeuwt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xztfpeeuwt .gt_font_normal {\n  font-weight: normal;\n}\n\n#xztfpeeuwt .gt_font_bold {\n  font-weight: bold;\n}\n\n#xztfpeeuwt .gt_font_italic {\n  font-style: italic;\n}\n\n#xztfpeeuwt .gt_super {\n  font-size: 65%;\n}\n\n#xztfpeeuwt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xztfpeeuwt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xztfpeeuwt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xztfpeeuwt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xztfpeeuwt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xztfpeeuwt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xztfpeeuwt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xztfpeeuwt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xztfpeeuwt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Summary-Statistic\">Summary Statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Command\">Command</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Mean</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">mean(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Standard Deviation</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">sd(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Median</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">median(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Minimum</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">min(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Maximum</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">max(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Interquartile Range</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">IQR(...)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">First quartile</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">quantile(..., 0.25)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Third quartile</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">quantile(..., 0.75)</td></tr>\n    <tr><td headers=\"Summary Statistic\" class=\"gt_row gt_left\">Five point summary</td>\n<td headers=\"Command\" class=\"gt_row gt_left\">summary(...)</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nLet's take a look at calculating descriptive statistics for `body_mass_g`, which describes the body mass of each penguin in grams.\n\nNow we can attach the cleaned `penguins` dataset. Attaching the dataset allows us to call variables directly by name. If we don’t attach it, we can still access variables, but we need to use the full format (for example, `clean_penguins$sex`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Attach cleaned dataset \nattach(clean_penguins)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's first calculate the mean and round it to one decimal place\nround(mean(body_mass_g),1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4207.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Now we can calculate the standard deviation\nround(sd(body_mass_g),1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 805.2\n```\n\n\n:::\n:::\n\n\nThe average body mass of penguins is **4207.1 g**, with a standard deviation of **805.2 g**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate the minimum\nmin(body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2700\n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate the maximum\nmax(body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6300\n```\n\n\n:::\n:::\n\n\nThe minimum observed body mass is **2700 g**, and the maximum observed body mass is **6300 g**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate median\nmedian(body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4050\n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate IQR\n## first quantile\nquantile(body_mass_g, 0.25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 25% \n3550 \n```\n\n\n:::\n\n```{.r .cell-code}\n## third quantile \nquantile(body_mass_g, 0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 75% \n4775 \n```\n\n\n:::\n:::\n\n\nThe median body mass is **4050 g**, with an interquartile range from **3350 g to 4775 g.**\n\nThe `summary()` function lets us quickly gather all of this information at once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate 5-point summary\nsummary(body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   2700    3550    4050    4207    4775    6300 \n```\n\n\n:::\n:::\n\n\nNow that we’ve explored numerical summaries, let’s move on to graphing.\n\nWhen you have one numerical variable, whether discrete or continuous, a **histogram** is a great way to visualise its distribution.\n\nWe’ll use the `ggplot2` package for this. If you haven’t used it before, you’ll need to install it first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install the package\ninstall.packages(ggplot2)\n```\n:::\n\n\nOnce installed, you can load the package and start plotting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the library\nlibrary(ggplot2)\n\n# We can plot the histogram\nggplot(clean_penguins, aes(x=body_mass_g))+\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThe histogram looks a bit plain without any color, and the x-axis label isn’t very informative. Let’s add some color, fix the labels, and give it a clean white background.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can plot the histogram\nggplot(clean_penguins, aes(x=body_mass_g))+\n  geom_histogram(fill=\"orangered\", bins=30) +\n  labs(x=\"Body Mass of Penguins (g)\")+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nWhat if we’re interested in how body mass relates to flipper length? In this case, we’re working with two continuous numerical variables, so a **scatterplot** would be a good choice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean_penguins, aes(x=body_mass_g, y=flipper_length_mm))+\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nLike we did with the histogram, we can add color, change the shape of the points, and include informative labels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean_penguins, aes(x=body_mass_g, y=flipper_length_mm))+\n  geom_point(fill=\"aquamarine\", col=\"aquamarine4\", pch=21, size=2.5)+\n  labs(x=\"Body Mass of Penguins (g)\", y=\"Flipper Length of Penguins (mm)\")+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nWe can see that as the body mass of a penguin increases, its flipper length also tends to increase. This suggests a *strong positive linear* relationship.\n\nNow, let’s look at a case where we have one categorical variable and one numerical variable. A **boxplot** is a great choice here. Let’s see how body mass differs between penguin species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean_penguins, aes(x=species, y=body_mass_g))+\n  geom_boxplot(fill = c(\"coral2\", \"chartreuse2\", \"cadetblue2\"),\n               col = c(\"coral3\", \"chartreuse4\", \"cadetblue4\")) +\n  labs(x=\"Species of Penguin\", y=\"Body Mass (g)\")\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nWe can see that Gentoo penguins have a noticeably higher median body mass compared to Chinstrap and Adelie penguins. The interquartile range (the box) for the Gentoo species does not overlap with the others, suggesting there may be a significant difference between them.\n\nSince we’re now considering species, let’s also take a look at how many penguins were observed in each species. Because we’re dealing with a categorical variable, a **bar plot** is appropriate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean_penguins, aes(x = species)) +\n  geom_bar(fill = c(\"coral2\", \"chartreuse2\", \"cadetblue2\"),\n               col = c(\"coral3\", \"chartreuse4\", \"cadetblue4\")) +\n  labs(x = \"Penguin Species\", y = \"Count\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nWe can also explore proportions to understand how each species contributes to the total sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=clean_penguins, aes(x=species))+\n  geom_bar(fill = c(\"coral2\", \"chartreuse2\", \"cadetblue2\"),\n               col = c(\"coral3\", \"chartreuse4\", \"cadetblue4\"), \n           aes(y=after_stat(prop), group=1))+\n  labs(x=\"Penguin Species\", y=\"Proportion\")+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nAdelie penguins make up a much larger proportion of the sample, while Chinstrap penguins account for the smallest. It’s important to consider how such imbalances in your dataset could influence your interpretation.\n\nWe can also generate a **mosaic plot** for species. To do so, we will need to install `ggmosaic`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"ggmosaic\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggmosaic)\n\nggplot(data=clean_penguins, aes(col=species))+\n  geom_mosaic(aes(x=product(species)), fill=c(\"coral2\", \"chartreuse2\", \"cadetblue2\"))+\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nThe wider the tile, the greater the proportion that species contributes. Adelie has the widest tile, which confirms it makes up the largest share of the sample.\n\nWhat if we want to look at penguin species by the island where they were observed? We are now dealing with two categorical variables. Mosaic plots work well here too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean_penguins) +\n  geom_mosaic(aes(x = product(island, species)), \n              fill = rep(c(\"coral2\", \"chartreuse2\", \"cadetblue2\"),3)) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](chapter1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nFrom this plot you can see:\n\n-   Adelie appear on Biscoe, Dream, and Torgersen in roughly similar counts.\n\n-   Chinstrap are observed only on Dream.\n\n-   Gentoo are observed only on Biscoe.\n\nThese patterns help explain why Adelie dominate overall, and they also show that species presence varies by island.\n\nBe sure to `detach()` your dataset before you move onto the exercises.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetach(clean_penguins)\n```\n:::\n\n\n## Exercise Checkpoint 2\n\n1.  Now that you are more comfortable generating plots and summary statistics in R, it is a good time to test your skills on a new dataset, the built-in **iris** dataset. This dataset is already preloaded in RStudio, so there is no need to import anything.\n\n    To make sure it is available, you can view it by running\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    View(iris)\n    ```\n    :::\n\n\n    This will open the dataset in a new tab in RStudio so you can explore its structure and variables before starting your analysis.\n\n    a\\. How many variables are in the `iris` dataset? <input class='webex-solveme nospaces' size='1' data-answer='[\"5\"]'/>\n\n    b\\. How many observations are in the `iris` dataset? <input class='webex-solveme nospaces' size='3' data-answer='[\"150\"]'/>\n\n    c\\. How many categorical variables are in the `iris` dataset? <input class='webex-solveme nospaces' size='1' data-answer='[\"1\"]'/>\n\n    d\\. How many numerical variables are in the `iris` dataset? <input class='webex-solveme nospaces' size='1' data-answer='[\"4\"]'/>\n\n    e\\. How many species are in the `iris` dataset? <input class='webex-solveme nospaces' size='1' data-answer='[\"3\"]'/>\n\n    f\\. What are the names of the three species in the `iris` dataset? Please list them in **alphabetical order**, separated by commas (for example: `x, y, z`) <input class='webex-solveme nospaces ignorecase regex' size='29' data-answer='[\"setosa, versicolor, virginica\"]'/>\n\n    g\\. Is `Species` nominal or ordinal? <input class='webex-solveme nospaces ignorecase regex' size='7' data-answer='[\"nominal\"]'/>\n\n    h\\. Is `Sepal.Length` continuous or discrete? <input class='webex-solveme nospaces ignorecase regex' size='10' data-answer='[\"continuous\"]'/>\n\n    i\\. What is the mean sepal width of iris varieties rounded to one decimal place? <input class='webex-solveme nospaces' size='3' data-answer='[\"3.1\"]'/>\n\n    j\\. What is an appropriate plot to visualise petal width against species? <input class='webex-solveme nospaces ignorecase regex' size='7' data-answer='[\"boxplot\"]'/>\n\n    k\\. What is an appropriate plot to visualise petal width against sepal width? <input class='webex-solveme nospaces ignorecase regex' size='11' data-answer='[\"scatterplot\"]'/>\n\n2.  \n",
    "supporting": [
      "chapter1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}